### ISSUE TITLE
trouble validating selection of type

### ISSUE THREAD

**Issue by GalShaharabani** [GalShaharabani/Basic-HTML-CSS-JS#1]
HTML code:
`   <select name="type" required >
                <option selected disabled id="chooseType" value="Choose type">Choose type:</option>
                <option value="Admin" >Admin</option>
                <option value="Company">Company</option>
                <option value="Customer" >Customer</option>       
                </select>`

JavaScript code:
function validateType(){

    _**var type=document.getElementsByTagName("option").value;
        console.log(type);
        
      console.log("type is: "+typeof type);
      if (type===null) {
          console.log("type is null ");**_
          
      /*}
      else if(type){
          console.log("type has attribute");
          
      }
          
     if (type==="Choose type") {
         return false;
     } 
     return true;
    }*/
  
  validateType();

**Comment by MichaelZhebov** [comment]
1. You must initialize your js code in the end of html code:
``` html 
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="style1.css">

</head>

<body>
    HTML code:
    <select id="type" required>
        <option selected disabled id="chooseType" value="Choose type">Choose type:</option>
        <option id="chooseType" value="Admin">Admin</option>
        <option id="chooseType" value="Company">Company</option>
        <option id="chooseType" value="Customer">Customer</option>
    </select>
</body>
<script src="site17.js"></script>
</html>
```
2. You must get element by "getElementById().value":
```js
function validateType() {
    var type = document.getElementById("type").value;
    console.log(type);
    console.log("type is: " + typeof type);

    if (type === null) {
        console.log("type is null ");
    } else if (type) {
        console.log("type has attribute");
    }

    if (type === "Choose type") {
        return false;
    }
    return true;
}
validateType();
```

The output:
**Choose type
type is: string
type has attribute**
This output always is "Choose type" because when the html code is loading a value of "select" is "Choose type".
3. If you want to differents outputs in the select, you must add a listener to your code.
Add _onchange="myFunction()"_ to "select" tag, and _myFunction()_ :
```html
<select id="type" onchange="myFunction()" required>
```
``` js
function myFunction() {
    var type = document.getElementById("type").value;
    console.log(type);
}
```
enjoy =)
